### ISSUE TITLE
Xenome Index build doesn't terminate

### ISSUE THREAD

**Issue by DeepakSharmaElucidata** [data61/gossamer#20]
Hi All,

I ran Xenome to build indexes for mouse and human reference genomes downloaded from UCSC. It has been almost 1 day and some hours since I have run it. It doesn't get terminated. I have read other issues mentioned on this Repo around Xenome classify command but didn't see any issues related to indexing. I am using an ubuntu machine with 32GB RAM and 250 hard disk.
Can anyone help me understand why this might be happening?

Thanks in advance!
Deepak

**Comment by Deguerre** [comment]
Hi. This is a known bug. Please read #9 .
