### ISSUE TITLE
Installation on mac OS

### ISSUE THREAD

**Issue by Tebalde0** [data61/gossamer#25]
Hello,
Just a workaround to install gossamer on recent Mac OS system and probably all Linux distribution, I guess. We had to remove the line 98 (${Boost_PROGRAM_OPTIONS_LIBRARY}) from  src/CMakeLists.txt in order to pass through the library accessibility check of cmake since the 
declaration of Boost library have nothing to do in such place.
Best,

**Comment by Deguerre** [comment]
Thanks for that!
