### ISSUE TITLE
index-both.header:No such file or directory

### ISSUE THREAD

**Issue by Himalayan-Java** [data61/gossamer#35]
I am having issue with xenome classify step. I am geeting following error message.
error performing classify:
        '/path/to/folder/index-both.header': No such file or directory
I check the folder. There was no such file. So, I assume index-both.header file was not generated during indexing step.
I tried to index the genome again, it does not generate the requred file.
Any suggestion on troubleshooting  !!

**Comment by Himalayan-Java** [comment]
Update: I was able to generate the index and run classify step.
Here are some changes I made:
1. use a single thread i.e -T =1 ( wait time is frustrating)
2. use unzipped file i.e. <gunzip file.fa> (not ideal)

**Comment by zyyy97** [comment]
Hi, I had the same problem
