### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by SyeonJe** [data61/gossamer#36]
Hi,
During installation Gossamer through CMAKE,I met this kind of error. 

---------error message---------

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- This is a Unix-like platform
-- The compiler is GNU
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48.0") found components: system iostreams program_options filesystem 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found Sqlite: /usr/include  
-- Looking for pandoc - found
--   Manual pages will be built
-- Configuring done
CMake Error at src/CMakeLists.txt:56 (ADD_LIBRARY):
  Cannot find source file:

    Boost::program_options

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at src/CMakeLists.txt:56 (ADD_LIBRARY):
  No SOURCES given to target: gossapp

CMake Generate step failed.  Build files cannot be regenerated correctly.

---------End---------

It said that there is no sources given to target, gossapp. how can i solve this problem? many thanks

**Comment by ForrestCKoch** [comment]
I'm having the same issue (with Boost 1.83).  Installing to 6.2.16-2-MANJARO.

```
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- This is a Unix-like platform
-- The compiler is GNU
-- Found Boost: /usr/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found suitable version "1.83.0", minimum required is "1.48.0") found components: system iostreams p>
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/libz.so (found version "1.3")
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.43.1
-- Found Sqlite: /usr/include
-- Looking for pandoc - found
--   Manual pages will be built
-- Configuring done (0.5s)
CMake Error at src/CMakeLists.txt:56 (ADD_LIBRARY):
  Cannot find source file:

    Boost::program_options

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:56 (ADD_LIBRARY):
  No SOURCES given to target: gossapp

```

**Comment by ForrestCKoch** [comment]
I might just leave a quick update here for anyone that happens to stumble across this and is struggling with the same issue.

The issue appears to be that Gossamer is not compatible with newer versions of Boost.  It sounds like it would be as simple as installing an older version of Boost, but this introduced a whole other range of compilation issues I won't get into.

The best way I could find to compile Gossamer was to download a fresh Docker image of Ubuntu 16.04 and proceed with installation as suggested in the README.

**Comment by andersx** [comment]
Use the version of `src/CmakeLists.txt` found here: https://github.com/data61/gossamer/pull/26

**Comment by Deguerre** [comment]
Thanks for that. I merged the PR.
